// ========== GO FISH! EXPANSION PACK DATA ==========
// Total Value: $50 - Premium Fishing Experience

// ========== 100 FISH TYPES (including 10 Super Rare) ==========
export const EXPANSION_FISH = [
  // Common Fish (40 types) - Points: 10-50
  { id: 1, name: 'Minnow', size: 15, rarity: 'common', points: 10, color: '#8B5A2B', habitat: 'Lake', desc: 'Tiny but tasty' },
  { id: 2, name: 'Bluegill', size: 20, rarity: 'common', points: 12, color: '#4169E1', habitat: 'Lake', desc: 'Blue beauty' },
  { id: 3, name: 'Perch', size: 25, rarity: 'common', points: 15, color: '#4CAF50', habitat: 'River', desc: 'Green stripes' },
  { id: 4, name: 'Sunfish', size: 18, rarity: 'common', points: 14, color: '#FFB347', habitat: 'Lake', desc: 'Sunny swimmer' },
  { id: 5, name: 'Crappie', size: 22, rarity: 'common', points: 18, color: '#A9A9A9', habitat: 'Lake', desc: 'Speckled friend' },
  { id: 6, name: 'Shad', size: 20, rarity: 'common', points: 11, color: '#C0C0C0', habitat: 'River', desc: 'Fast school fish' },
  { id: 7, name: 'Carp', size: 45, rarity: 'common', points: 25, color: '#CD853F', habitat: 'Lake', desc: 'Bottom feeder' },
  { id: 8, name: 'Bullhead', size: 28, rarity: 'common', points: 20, color: '#3D3D3D', habitat: 'River', desc: 'Whiskered wonder' },
  { id: 9, name: 'Rock Bass', size: 24, rarity: 'common', points: 22, color: '#8B4513', habitat: 'Lake', desc: 'Rocky hideout' },
  { id: 10, name: 'Pumpkinseed', size: 16, rarity: 'common', points: 13, color: '#FF7F50', habitat: 'Lake', desc: 'Colorful catch' },
  { id: 11, name: 'Yellow Perch', size: 26, rarity: 'common', points: 19, color: '#FFD700', habitat: 'Lake', desc: 'Golden stripes' },
  { id: 12, name: 'White Bass', size: 32, rarity: 'common', points: 28, color: '#F5F5F5', habitat: 'River', desc: 'Silver flash' },
  { id: 13, name: 'Channel Cat', size: 50, rarity: 'common', points: 35, color: '#696969', habitat: 'River', desc: 'Night hunter' },
  { id: 14, name: 'Drum', size: 38, rarity: 'common', points: 24, color: '#808080', habitat: 'River', desc: 'Makes noise!' },
  { id: 15, name: 'Gar', size: 60, rarity: 'common', points: 40, color: '#556B2F', habitat: 'River', desc: 'Ancient fish' },
  { id: 16, name: 'Bowfin', size: 55, rarity: 'common', points: 38, color: '#2F4F4F', habitat: 'Swamp', desc: 'Living fossil' },
  { id: 17, name: 'Buffalo', size: 48, rarity: 'common', points: 32, color: '#8B8682', habitat: 'River', desc: 'Big mouth' },
  { id: 18, name: 'Sucker', size: 35, rarity: 'common', points: 21, color: '#A0522D', habitat: 'River', desc: 'Lip service' },
  { id: 19, name: 'Chub', size: 22, rarity: 'common', points: 16, color: '#B8860B', habitat: 'Stream', desc: 'Chunky boy' },
  { id: 20, name: 'Dace', size: 18, rarity: 'common', points: 14, color: '#DAA520', habitat: 'Stream', desc: 'Quick silver' },
  { id: 21, name: 'Shiner', size: 12, rarity: 'common', points: 10, color: '#E6E6FA', habitat: 'Lake', desc: 'Tiny sparkle' },
  { id: 22, name: 'Sculpin', size: 14, rarity: 'common', points: 12, color: '#6B8E23', habitat: 'Stream', desc: 'Bottom dweller' },
  { id: 23, name: 'Darter', size: 10, rarity: 'common', points: 11, color: '#FF6347', habitat: 'Stream', desc: 'Speedy small' },
  { id: 24, name: 'Madtom', size: 12, rarity: 'common', points: 13, color: '#4A4A4A', habitat: 'Stream', desc: 'Mini catfish' },
  { id: 25, name: 'Killifish', size: 8, rarity: 'common', points: 10, color: '#40E0D0', habitat: 'Marsh', desc: 'Mosquito eater' },
  { id: 26, name: 'Topminnow', size: 10, rarity: 'common', points: 10, color: '#98FB98', habitat: 'Pond', desc: 'Surface skimmer' },
  { id: 27, name: 'Mudminnow', size: 14, rarity: 'common', points: 11, color: '#8B7355', habitat: 'Swamp', desc: 'Mud lover' },
  { id: 28, name: 'Pickerel', size: 35, rarity: 'common', points: 30, color: '#228B22', habitat: 'Lake', desc: 'Baby pike' },
  { id: 29, name: 'Warmouth', size: 24, rarity: 'common', points: 20, color: '#9ACD32', habitat: 'Pond', desc: 'War paint' },
  { id: 30, name: 'Flier', size: 18, rarity: 'common', points: 15, color: '#7CFC00', habitat: 'Swamp', desc: 'High jumper' },
  { id: 31, name: 'Mooneye', size: 30, rarity: 'common', points: 26, color: '#F0E68C', habitat: 'River', desc: 'Big eyes' },
  { id: 32, name: 'Goldeye', size: 32, rarity: 'common', points: 28, color: '#FFD700', habitat: 'River', desc: 'Golden gaze' },
  { id: 33, name: 'Smelt', size: 18, rarity: 'common', points: 16, color: '#B0E0E6', habitat: 'Lake', desc: 'Tasty treat' },
  { id: 34, name: 'Alewife', size: 22, rarity: 'common', points: 18, color: '#ADD8E6', habitat: 'Lake', desc: 'Herring cousin' },
  { id: 35, name: 'Cisco', size: 28, rarity: 'common', points: 24, color: '#87CEEB', habitat: 'Lake', desc: 'Cold water' },
  { id: 36, name: 'Whitefish', size: 40, rarity: 'common', points: 35, color: '#FFFAFA', habitat: 'Lake', desc: 'Deep diver' },
  { id: 37, name: 'Burbot', size: 45, rarity: 'common', points: 38, color: '#8B8378', habitat: 'Lake', desc: 'Freshwater cod' },
  { id: 38, name: 'Sculpin', size: 16, rarity: 'common', points: 14, color: '#708090', habitat: 'Stream', desc: 'Rock hugger' },
  { id: 39, name: 'Logperch', size: 14, rarity: 'common', points: 12, color: '#D2691E', habitat: 'River', desc: 'Log roller' },
  { id: 40, name: 'Sauger', size: 38, rarity: 'common', points: 42, color: '#BDB76B', habitat: 'River', desc: 'Sandy eyes' },
  
  // Uncommon Fish (30 types) - Points: 50-150
  { id: 41, name: 'Largemouth Bass', size: 55, rarity: 'uncommon', points: 60, color: '#228B22', habitat: 'Lake', desc: 'Big mouth hunter' },
  { id: 42, name: 'Smallmouth Bass', size: 45, rarity: 'uncommon', points: 55, color: '#8B4513', habitat: 'River', desc: 'Bronze beauty' },
  { id: 43, name: 'Spotted Bass', size: 42, rarity: 'uncommon', points: 52, color: '#6B8E23', habitat: 'River', desc: 'Spotted fighter' },
  { id: 44, name: 'Striped Bass', size: 75, rarity: 'uncommon', points: 90, color: '#708090', habitat: 'Ocean', desc: 'Striper power' },
  { id: 45, name: 'Northern Pike', size: 85, rarity: 'uncommon', points: 100, color: '#2E8B57', habitat: 'Lake', desc: 'Water wolf' },
  { id: 46, name: 'Muskellunge', size: 100, rarity: 'uncommon', points: 120, color: '#3CB371', habitat: 'Lake', desc: 'Muskie madness' },
  { id: 47, name: 'Walleye', size: 65, rarity: 'uncommon', points: 80, color: '#F4A460', habitat: 'Lake', desc: 'Glass eyes' },
  { id: 48, name: 'Yellow Catfish', size: 70, rarity: 'uncommon', points: 85, color: '#FFD700', habitat: 'River', desc: 'Flathead fighter' },
  { id: 49, name: 'Blue Catfish', size: 90, rarity: 'uncommon', points: 110, color: '#4682B4', habitat: 'River', desc: 'River monster' },
  { id: 50, name: 'Rainbow Trout', size: 50, rarity: 'uncommon', points: 70, color: '#FF69B4', habitat: 'Stream', desc: 'Rainbow flash' },
  { id: 51, name: 'Brown Trout', size: 55, rarity: 'uncommon', points: 75, color: '#8B4513', habitat: 'Stream', desc: 'Spotted brown' },
  { id: 52, name: 'Brook Trout', size: 35, rarity: 'uncommon', points: 58, color: '#00CED1', habitat: 'Stream', desc: 'Brook beauty' },
  { id: 53, name: 'Lake Trout', size: 70, rarity: 'uncommon', points: 95, color: '#696969', habitat: 'Lake', desc: 'Deep lake king' },
  { id: 54, name: 'Steelhead', size: 65, rarity: 'uncommon', points: 88, color: '#C0C0C0', habitat: 'River', desc: 'Chrome bullet' },
  { id: 55, name: 'Salmon', size: 75, rarity: 'uncommon', points: 100, color: '#FA8072', habitat: 'River', desc: 'Leaping legend' },
  { id: 56, name: 'Coho Salmon', size: 70, rarity: 'uncommon', points: 92, color: '#E9967A', habitat: 'Ocean', desc: 'Silver salmon' },
  { id: 57, name: 'Chinook Salmon', size: 85, rarity: 'uncommon', points: 115, color: '#CD5C5C', habitat: 'Ocean', desc: 'King salmon' },
  { id: 58, name: 'Sockeye Salmon', size: 60, rarity: 'uncommon', points: 78, color: '#DC143C', habitat: 'River', desc: 'Red runner' },
  { id: 59, name: 'Pink Salmon', size: 50, rarity: 'uncommon', points: 65, color: '#FFB6C1', habitat: 'Ocean', desc: 'Pink prize' },
  { id: 60, name: 'Tiger Muskie', size: 95, rarity: 'uncommon', points: 130, color: '#FFA500', habitat: 'Lake', desc: 'Striped terror' },
  { id: 61, name: 'Hybrid Striper', size: 68, rarity: 'uncommon', points: 82, color: '#778899', habitat: 'Lake', desc: 'Wiper fighter' },
  { id: 62, name: 'Saugeye', size: 48, rarity: 'uncommon', points: 62, color: '#DAA520', habitat: 'Lake', desc: 'Hybrid hunter' },
  { id: 63, name: 'Splake', size: 52, rarity: 'uncommon', points: 68, color: '#BC8F8F', habitat: 'Lake', desc: 'Trout hybrid' },
  { id: 64, name: 'Tiger Trout', size: 45, rarity: 'uncommon', points: 60, color: '#FF8C00', habitat: 'Stream', desc: 'Tiger stripes' },
  { id: 65, name: 'Peacock Bass', size: 60, rarity: 'uncommon', points: 85, color: '#32CD32', habitat: 'Lake', desc: 'Tropical terror' },
  { id: 66, name: 'Snook', size: 70, rarity: 'uncommon', points: 95, color: '#F5DEB3', habitat: 'Coast', desc: 'Line sider' },
  { id: 67, name: 'Redfish', size: 65, rarity: 'uncommon', points: 88, color: '#B22222', habitat: 'Coast', desc: 'Red drum' },
  { id: 68, name: 'Tarpon', size: 120, rarity: 'uncommon', points: 150, color: '#C0C0C0', habitat: 'Coast', desc: 'Silver king' },
  { id: 69, name: 'Bonefish', size: 55, rarity: 'uncommon', points: 72, color: '#D3D3D3', habitat: 'Flats', desc: 'Ghost fish' },
  { id: 70, name: 'Permit', size: 50, rarity: 'uncommon', points: 68, color: '#A9A9A9', habitat: 'Flats', desc: 'Flat fighter' },
  
  // Rare Fish (20 types) - Points: 150-500
  { id: 71, name: 'Golden Koi', size: 60, rarity: 'rare', points: 200, color: '#FFD700', habitat: 'Pond', desc: 'Lucky gold' },
  { id: 72, name: 'Platinum Koi', size: 65, rarity: 'rare', points: 250, color: '#E5E4E2', habitat: 'Pond', desc: 'Platinum beauty' },
  { id: 73, name: 'Giant Catfish', size: 150, rarity: 'rare', points: 300, color: '#4A4A4A', habitat: 'River', desc: 'River giant' },
  { id: 74, name: 'Sturgeon', size: 180, rarity: 'rare', points: 350, color: '#696969', habitat: 'River', desc: 'Ancient giant' },
  { id: 75, name: 'Paddlefish', size: 140, rarity: 'rare', points: 280, color: '#708090', habitat: 'River', desc: 'Paddle nose' },
  { id: 76, name: 'Alligator Gar', size: 200, rarity: 'rare', points: 400, color: '#556B2F', habitat: 'River', desc: 'Gator fish' },
  { id: 77, name: 'Blue Marlin', size: 250, rarity: 'rare', points: 450, color: '#4169E1', habitat: 'Ocean', desc: 'Ocean sword' },
  { id: 78, name: 'Swordfish', size: 220, rarity: 'rare', points: 420, color: '#483D8B', habitat: 'Ocean', desc: 'Blade nose' },
  { id: 79, name: 'Sailfish', size: 200, rarity: 'rare', points: 380, color: '#6A5ACD', habitat: 'Ocean', desc: 'Speed demon' },
  { id: 80, name: 'Yellowfin Tuna', size: 180, rarity: 'rare', points: 350, color: '#FFD700', habitat: 'Ocean', desc: 'Yellow rocket' },
  { id: 81, name: 'Bluefin Tuna', size: 250, rarity: 'rare', points: 500, color: '#00008B', habitat: 'Ocean', desc: 'Ocean royalty' },
  { id: 82, name: 'Mahi Mahi', size: 120, rarity: 'rare', points: 220, color: '#00FF7F', habitat: 'Ocean', desc: 'Dolphin fish' },
  { id: 83, name: 'Wahoo', size: 150, rarity: 'rare', points: 280, color: '#4682B4', habitat: 'Ocean', desc: 'Speed king' },
  { id: 84, name: 'Giant Trevally', size: 140, rarity: 'rare', points: 260, color: '#2F4F4F', habitat: 'Reef', desc: 'GT power' },
  { id: 85, name: 'Roosterfish', size: 100, rarity: 'rare', points: 200, color: '#FF6347', habitat: 'Coast', desc: 'Mohawk fish' },
  { id: 86, name: 'Cubera Snapper', size: 110, rarity: 'rare', points: 230, color: '#8B0000', habitat: 'Reef', desc: 'Big red' },
  { id: 87, name: 'Goliath Grouper', size: 300, rarity: 'rare', points: 480, color: '#8B8378', habitat: 'Reef', desc: 'Reef giant' },
  { id: 88, name: 'Arapaima', size: 280, rarity: 'rare', points: 450, color: '#CD853F', habitat: 'River', desc: 'Amazon beast' },
  { id: 89, name: 'Barramundi', size: 120, rarity: 'rare', points: 240, color: '#C0C0C0', habitat: 'River', desc: 'Aussie bass' },
  { id: 90, name: 'Peacock Cichlid', size: 40, rarity: 'rare', points: 180, color: '#FF1493', habitat: 'Lake', desc: 'Rainbow cichlid' },
  
  // SUPER RARE FISH (10 types) - Points: 1000-5000
  { id: 91, name: 'Mythic Golden Dragon', size: 300, rarity: 'super_rare', points: 1000, color: '#FFD700', habitat: 'Legend', desc: '🐉 Dragon of wealth', glow: true },
  { id: 92, name: 'Crystal Phantom', size: 150, rarity: 'super_rare', points: 1500, color: '#E0FFFF', habitat: 'Abyss', desc: '👻 Invisible hunter', glow: true },
  { id: 93, name: 'Volcanic Inferno', size: 200, rarity: 'super_rare', points: 2000, color: '#FF4500', habitat: 'Volcano', desc: '🔥 Born in fire', glow: true },
  { id: 94, name: 'Abyssal Leviathan', size: 500, rarity: 'super_rare', points: 2500, color: '#191970', habitat: 'Abyss', desc: '🌊 Deep sea terror', glow: true },
  { id: 95, name: 'Aurora Borealis', size: 180, rarity: 'super_rare', points: 3000, color: '#7FFFD4', habitat: 'Arctic', desc: '✨ Northern lights', glow: true },
  { id: 96, name: 'Shadow Specter', size: 160, rarity: 'super_rare', points: 3500, color: '#2F2F2F', habitat: 'Night', desc: '🌑 Darkness incarnate', glow: true },
  { id: 97, name: 'Celestial Starfish', size: 100, rarity: 'super_rare', points: 4000, color: '#9370DB', habitat: 'Space', desc: '⭐ Star walker', glow: true },
  { id: 98, name: 'Ancient Fossil King', size: 400, rarity: 'super_rare', points: 4500, color: '#DEB887', habitat: 'Time', desc: '👑 Time traveler', glow: true },
  { id: 99, name: 'Rainbow Serpent', size: 350, rarity: 'super_rare', points: 5000, color: '#FF69B4', habitat: 'Rainbow', desc: '🌈 All colors', glow: true },
  { id: 100, name: 'The One Fish', size: 1, rarity: 'super_rare', points: 10000, color: '#FFFFFF', habitat: '???', desc: '🎯 The chosen one', glow: true },
];

// ========== 10 RODS ==========
export const EXPANSION_RODS = [
  { id: 1, name: 'Bamboo Rod', castDistance: 150, reelSpeed: 1.0, durability: 80, price: 0, color: '#8B7355', desc: 'Starter rod' },
  { id: 2, name: 'Fiberglass Rod', castDistance: 180, reelSpeed: 1.2, durability: 100, price: 2.99, color: '#B0C4DE', desc: 'Reliable choice' },
  { id: 3, name: 'Carbon Rod', castDistance: 220, reelSpeed: 1.4, durability: 120, price: 4.99, color: '#2F4F4F', desc: 'Lightweight power' },
  { id: 4, name: 'Graphite Pro', castDistance: 260, reelSpeed: 1.6, durability: 140, price: 6.99, color: '#363636', desc: 'Pro level' },
  { id: 5, name: 'Titanium Elite', castDistance: 300, reelSpeed: 1.8, durability: 160, price: 8.99, color: '#708090', desc: 'Elite performance' },
  { id: 6, name: 'Crystal Clear', castDistance: 320, reelSpeed: 1.9, durability: 180, price: 9.99, color: '#E0FFFF', desc: 'See-through magic' },
  { id: 7, name: 'Thunder Strike', castDistance: 350, reelSpeed: 2.0, durability: 200, price: 11.99, color: '#FFD700', desc: 'Lightning fast' },
  { id: 8, name: 'Deep Sea Master', castDistance: 380, reelSpeed: 2.2, durability: 220, price: 13.99, color: '#00008B', desc: 'Ocean conqueror' },
  { id: 9, name: 'Dragon Slayer', castDistance: 400, reelSpeed: 2.4, durability: 250, price: 15.99, color: '#8B0000', desc: 'Legendary rod' },
  { id: 10, name: 'Poseidon\'s Trident', castDistance: 450, reelSpeed: 2.8, durability: 300, price: 19.99, color: '#00CED1', desc: 'God tier' },
];

// ========== 10 FISHING LINES ==========
export const EXPANSION_LINES = [
  { id: 1, name: 'Basic Mono', strength: 10, visibility: 0.8, price: 0, color: '#FFFFFF', desc: 'Standard line' },
  { id: 2, name: 'Braided Line', strength: 15, visibility: 0.6, price: 1.99, color: '#228B22', desc: 'Strong braid' },
  { id: 3, name: 'Fluorocarbon', strength: 18, visibility: 0.3, price: 2.99, color: '#E0FFFF', desc: 'Nearly invisible' },
  { id: 4, name: 'Steel Wire', strength: 25, visibility: 0.9, price: 3.99, color: '#C0C0C0', desc: 'For big fish' },
  { id: 5, name: 'Spider Silk', strength: 30, visibility: 0.2, price: 4.99, color: '#FFFAFA', desc: 'Nature\'s best' },
  { id: 6, name: 'Nano Fiber', strength: 35, visibility: 0.15, price: 5.99, color: '#7B68EE', desc: 'Future tech' },
  { id: 7, name: 'Mythril Thread', strength: 40, visibility: 0.1, price: 6.99, color: '#87CEEB', desc: 'Magical material' },
  { id: 8, name: 'Dragon Sinew', strength: 50, visibility: 0.3, price: 7.99, color: '#FF4500', desc: 'Fire resistant' },
  { id: 9, name: 'Ghost Line', strength: 55, visibility: 0.05, price: 8.99, color: '#F8F8FF', desc: 'Completely invisible' },
  { id: 10, name: 'Unbreakable', strength: 100, visibility: 0.2, price: 9.99, color: '#FFD700', desc: 'Never breaks' },
];

// ========== 50 STAGES ==========
export const EXPANSION_STAGES = [
  // Beginner Lakes (10)
  { id: 1, name: 'Sunny Lake', difficulty: 1, unlocked: true, price: 0, icon: '☀️', color: 'from-sky-400 to-cyan-500' },
  { id: 2, name: 'Crystal Pond', difficulty: 1, unlocked: true, price: 0, icon: '💎', color: 'from-cyan-400 to-blue-500' },
  { id: 3, name: 'Lily Pad Lake', difficulty: 1, unlocked: false, price: 0.99, icon: '🌸', color: 'from-pink-400 to-rose-500' },
  { id: 4, name: 'Frog Creek', difficulty: 1, unlocked: false, price: 0.99, icon: '🐸', color: 'from-green-400 to-emerald-500' },
  { id: 5, name: 'Duckling Bay', difficulty: 1, unlocked: false, price: 0.99, icon: '🦆', color: 'from-yellow-400 to-amber-500' },
  { id: 6, name: 'Butterfly Marsh', difficulty: 1, unlocked: false, price: 0.99, icon: '🦋', color: 'from-purple-400 to-violet-500' },
  { id: 7, name: 'Sunrise Cove', difficulty: 1, unlocked: false, price: 0.99, icon: '🌅', color: 'from-orange-400 to-red-500' },
  { id: 8, name: 'Rainbow Falls', difficulty: 1, unlocked: false, price: 0.99, icon: '🌈', color: 'from-red-400 via-yellow-400 to-blue-500' },
  { id: 9, name: 'Firefly Lake', difficulty: 1, unlocked: false, price: 0.99, icon: '✨', color: 'from-amber-400 to-yellow-500' },
  { id: 10, name: 'Moonlit Pond', difficulty: 1, unlocked: false, price: 0.99, icon: '🌙', color: 'from-slate-400 to-slate-600' },
  
  // Rivers (10)
  { id: 11, name: 'Rushing River', difficulty: 2, unlocked: false, price: 1.49, icon: '🏞️', color: 'from-blue-500 to-indigo-600' },
  { id: 12, name: 'Salmon Run', difficulty: 2, unlocked: false, price: 1.49, icon: '🐟', color: 'from-rose-500 to-pink-600' },
  { id: 13, name: 'Waterfall Basin', difficulty: 2, unlocked: false, price: 1.49, icon: '💧', color: 'from-cyan-500 to-blue-600' },
  { id: 14, name: 'Canyon Stream', difficulty: 2, unlocked: false, price: 1.49, icon: '🏜️', color: 'from-orange-500 to-red-600' },
  { id: 15, name: 'Glacier Melt', difficulty: 2, unlocked: false, price: 1.49, icon: '🏔️', color: 'from-slate-300 to-blue-400' },
  { id: 16, name: 'Jungle Rapids', difficulty: 2, unlocked: false, price: 1.49, icon: '🌴', color: 'from-green-500 to-emerald-600' },
  { id: 17, name: 'Ancient River', difficulty: 2, unlocked: false, price: 1.49, icon: '🏛️', color: 'from-amber-600 to-yellow-700' },
  { id: 18, name: 'Misty Stream', difficulty: 2, unlocked: false, price: 1.49, icon: '🌫️', color: 'from-gray-400 to-slate-500' },
  { id: 19, name: 'Golden River', difficulty: 2, unlocked: false, price: 1.49, icon: '🥇', color: 'from-yellow-500 to-amber-600' },
  { id: 20, name: 'Thunder Creek', difficulty: 2, unlocked: false, price: 1.49, icon: '⚡', color: 'from-yellow-400 to-purple-600' },
  
  // Ocean Coasts (10)
  { id: 21, name: 'Sandy Beach', difficulty: 3, unlocked: false, price: 1.99, icon: '🏖️', color: 'from-yellow-400 to-orange-500' },
  { id: 22, name: 'Coral Reef', difficulty: 3, unlocked: false, price: 1.99, icon: '🐠', color: 'from-pink-500 to-orange-500' },
  { id: 23, name: 'Rocky Shore', difficulty: 3, unlocked: false, price: 1.99, icon: '🪨', color: 'from-gray-500 to-slate-600' },
  { id: 24, name: 'Pier Fishing', difficulty: 3, unlocked: false, price: 1.99, icon: '🌉', color: 'from-blue-600 to-indigo-700' },
  { id: 25, name: 'Lighthouse Bay', difficulty: 3, unlocked: false, price: 1.99, icon: '🗼', color: 'from-red-500 to-orange-600' },
  { id: 26, name: 'Shipwreck Cove', difficulty: 3, unlocked: false, price: 1.99, icon: '🚢', color: 'from-slate-600 to-gray-700' },
  { id: 27, name: 'Tropical Paradise', difficulty: 3, unlocked: false, price: 1.99, icon: '🏝️', color: 'from-teal-400 to-cyan-500' },
  { id: 28, name: 'Whale Watch', difficulty: 3, unlocked: false, price: 1.99, icon: '🐋', color: 'from-blue-500 to-slate-600' },
  { id: 29, name: 'Sunset Harbor', difficulty: 3, unlocked: false, price: 1.99, icon: '⛵', color: 'from-orange-500 to-pink-600' },
  { id: 30, name: 'Dolphin Bay', difficulty: 3, unlocked: false, price: 1.99, icon: '🐬', color: 'from-cyan-400 to-blue-500' },
  
  // Deep Ocean (10)
  { id: 31, name: 'Deep Blue', difficulty: 4, unlocked: false, price: 2.49, icon: '🌊', color: 'from-blue-700 to-indigo-900' },
  { id: 32, name: 'Mariana Trench', difficulty: 4, unlocked: false, price: 2.49, icon: '🕳️', color: 'from-slate-800 to-black' },
  { id: 33, name: 'Bioluminescent', difficulty: 4, unlocked: false, price: 2.49, icon: '💡', color: 'from-cyan-500 to-purple-600' },
  { id: 34, name: 'Kraken\'s Lair', difficulty: 4, unlocked: false, price: 2.49, icon: '🦑', color: 'from-purple-700 to-indigo-900' },
  { id: 35, name: 'Atlantis Ruins', difficulty: 4, unlocked: false, price: 2.49, icon: '🏰', color: 'from-teal-600 to-blue-800' },
  { id: 36, name: 'Volcanic Vent', difficulty: 4, unlocked: false, price: 2.49, icon: '🌋', color: 'from-red-600 to-orange-800' },
  { id: 37, name: 'Ice Cavern', difficulty: 4, unlocked: false, price: 2.49, icon: '🧊', color: 'from-cyan-300 to-blue-500' },
  { id: 38, name: 'Pirate Graveyard', difficulty: 4, unlocked: false, price: 2.49, icon: '☠️', color: 'from-gray-700 to-slate-900' },
  { id: 39, name: 'Treasure Trove', difficulty: 4, unlocked: false, price: 2.49, icon: '💰', color: 'from-yellow-600 to-amber-800' },
  { id: 40, name: 'Mermaid\'s Garden', difficulty: 4, unlocked: false, price: 2.49, icon: '🧜', color: 'from-pink-500 to-purple-600' },
  
  // Extreme/Legendary (10)
  { id: 41, name: 'Storm of Ages', difficulty: 5, unlocked: false, price: 2.99, icon: '⛈️', color: 'from-gray-600 to-purple-800' },
  { id: 42, name: 'Frozen Tundra', difficulty: 5, unlocked: false, price: 2.99, icon: '❄️', color: 'from-blue-300 to-cyan-500' },
  { id: 43, name: 'Lava Lake', difficulty: 5, unlocked: false, price: 2.99, icon: '🔥', color: 'from-red-500 to-orange-700' },
  { id: 44, name: 'Toxic Swamp', difficulty: 5, unlocked: false, price: 2.99, icon: '☢️', color: 'from-green-500 to-lime-700' },
  { id: 45, name: 'Haunted Waters', difficulty: 5, unlocked: false, price: 2.99, icon: '👻', color: 'from-slate-700 to-purple-900' },
  { id: 46, name: 'Dragon\'s Lake', difficulty: 5, unlocked: false, price: 2.99, icon: '🐉', color: 'from-red-600 to-yellow-600' },
  { id: 47, name: 'Starlight Ocean', difficulty: 5, unlocked: false, price: 2.99, icon: '🌟', color: 'from-indigo-600 to-purple-800' },
  { id: 48, name: 'Time Vortex', difficulty: 5, unlocked: false, price: 2.99, icon: '⏳', color: 'from-amber-500 to-teal-600' },
  { id: 49, name: 'Dimension Rift', difficulty: 5, unlocked: false, price: 2.99, icon: '🌀', color: 'from-purple-500 via-pink-500 to-cyan-500' },
  { id: 50, name: 'The Final Cast', difficulty: 5, unlocked: false, price: 2.99, icon: '👑', color: 'from-yellow-400 via-red-500 to-purple-600' },
];

// ========== IMPROVED TACKLEBOX ==========
export const TACKLEBOX_UPGRADES = [
  { id: 1, name: 'Basic Box', slots: 10, features: ['Store 10 fish'], price: 0, icon: '📦' },
  { id: 2, name: 'Wooden Chest', slots: 25, features: ['Store 25 fish', 'Auto-sort'], price: 2.99, icon: '🪵' },
  { id: 3, name: 'Metal Case', slots: 50, features: ['Store 50 fish', 'Auto-sort', 'Stats view'], price: 4.99, icon: '🔧' },
  { id: 4, name: 'Pro Organizer', slots: 100, features: ['Store 100 fish', 'Auto-sort', 'Stats', 'Filters'], price: 6.99, icon: '💼' },
  { id: 5, name: 'Legendary Vault', slots: 500, features: ['Store 500 fish', 'All features', 'Trophy room', 'Export'], price: 9.99, icon: '🏆' },
];

// ========== FISHING SKILL LEVELS ==========
export const FISHING_SKILLS = {
  casting: {
    name: 'Casting',
    icon: '🎯',
    levels: 20,
    bonusPerLevel: { castDistance: 5 },
    desc: 'Increase cast distance',
  },
  reeling: {
    name: 'Reeling',
    icon: '🔄',
    levels: 20,
    bonusPerLevel: { reelSpeed: 0.05 },
    desc: 'Faster reel speed',
  },
  patience: {
    name: 'Patience',
    icon: '⏳',
    levels: 20,
    bonusPerLevel: { biteChance: 2 },
    desc: 'Better bite chances',
  },
  strength: {
    name: 'Strength',
    icon: '💪',
    levels: 20,
    bonusPerLevel: { tensionResist: 3 },
    desc: 'Handle more tension',
  },
  luck: {
    name: 'Luck',
    icon: '🍀',
    levels: 20,
    bonusPerLevel: { rareChance: 1 },
    desc: 'Find rarer fish',
  },
};

// ========== EXPANSION PACKAGES ==========
export const EXPANSION_PACKAGES = [
  {
    id: 'starter',
    name: 'Starter Pack',
    desc: '5 stages + 2 rods',
    items: ['5 stages', '2 rods', '2 lines'],
    originalPrice: 12.99,
    price: 4.99,
    discount: 62,
    icon: '🎁',
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'fisher',
    name: 'Fisher Pack',
    desc: '15 stages + 4 rods + skills',
    items: ['15 stages', '4 rods', '4 lines', 'Skill system'],
    originalPrice: 24.99,
    price: 9.99,
    discount: 60,
    icon: '🎣',
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'pro',
    name: 'Pro Pack',
    desc: '30 stages + 7 rods + tacklebox',
    items: ['30 stages', '7 rods', '7 lines', 'Pro Tacklebox', 'Skill system'],
    originalPrice: 39.99,
    price: 19.99,
    discount: 50,
    icon: '⭐',
    color: 'from-purple-500 to-violet-600',
  },
  {
    id: 'ultimate',
    name: 'ULTIMATE BUNDLE',
    desc: 'EVERYTHING! Best value!',
    items: ['ALL 50 stages', 'ALL 10 rods', 'ALL 15 bobbers', 'ALL 10 lines', 'ALL 5 difficulties', 'Legendary Tacklebox', 'All skills', '100 fish types', '10 Super Rare fish'],
    originalPrice: 89.99,
    price: 49.99,
    discount: 44,
    icon: '👑',
    color: 'from-yellow-400 via-red-500 to-purple-600',
    featured: true,
  },
];

// ========== 15 BOBBERS ==========
export const EXPANSION_BOBBERS = [
  { id: 1, name: 'Classic Red', visibility: 1.0, sensitivity: 1.0, price: 0, color: '#FF4444', desc: 'Traditional bobber' },
  { id: 2, name: 'Neon Orange', visibility: 1.2, sensitivity: 1.0, price: 0.99, color: '#FF6B00', desc: 'Bright orange' },
  { id: 3, name: 'Electric Yellow', visibility: 1.3, sensitivity: 1.1, price: 1.49, color: '#FFFF00', desc: 'Super visible' },
  { id: 4, name: 'Stealth Black', visibility: 0.5, sensitivity: 1.3, price: 1.99, color: '#1a1a1a', desc: 'Fish can\'t see it' },
  { id: 5, name: 'Camo Green', visibility: 0.6, sensitivity: 1.2, price: 1.99, color: '#4A5D23', desc: 'Blends with weeds' },
  { id: 6, name: 'Glow Night', visibility: 1.5, sensitivity: 1.1, price: 2.49, color: '#00FF88', desc: 'Glows in dark', glow: true },
  { id: 7, name: 'Deep Blue', visibility: 0.8, sensitivity: 1.2, price: 2.49, color: '#0066CC', desc: 'Ocean perfect' },
  { id: 8, name: 'Sunset Pink', visibility: 1.1, sensitivity: 1.0, price: 2.99, color: '#FF69B4', desc: 'Dusk favorite' },
  { id: 9, name: 'Ice Crystal', visibility: 1.4, sensitivity: 1.2, price: 3.49, color: '#E0FFFF', desc: 'Winter special', glow: true },
  { id: 10, name: 'Lava Flow', visibility: 1.3, sensitivity: 1.3, price: 3.99, color: '#FF4500', desc: 'Hot design', glow: true },
  { id: 11, name: 'Galaxy Purple', visibility: 1.2, sensitivity: 1.4, price: 4.49, color: '#9370DB', desc: 'Space themed', glow: true },
  { id: 12, name: 'Golden King', visibility: 1.4, sensitivity: 1.3, price: 4.99, color: '#FFD700', desc: 'Premium gold', glow: true },
  { id: 13, name: 'Rainbow Burst', visibility: 1.5, sensitivity: 1.2, price: 5.99, color: '#FF69B4', desc: 'Color changing', rainbow: true },
  { id: 14, name: 'Diamond Elite', visibility: 1.6, sensitivity: 1.5, price: 6.99, color: '#B9F2FF', desc: 'Crystal clear', glow: true },
  { id: 15, name: 'Legendary Orb', visibility: 2.0, sensitivity: 2.0, price: 9.99, color: '#FFFFFF', desc: 'Ultimate bobber', glow: true, legendary: true },
];

// ========== 5 DIFFICULTY SETTINGS (Above Normal) ==========
export const EXPANSION_DIFFICULTIES = [
  { 
    id: 1, 
    name: 'Hard', 
    desc: 'For experienced anglers',
    tensionMultiplier: 1.3,
    biteWindow: 1.2,
    fishStrength: 1.2,
    rewardMultiplier: 1.5,
    price: 0,
    color: 'from-orange-500 to-red-500',
    icon: '🔥',
    unlocked: true,
  },
  { 
    id: 2, 
    name: 'Expert', 
    desc: 'Test your skills',
    tensionMultiplier: 1.5,
    biteWindow: 1.0,
    fishStrength: 1.4,
    rewardMultiplier: 2.0,
    price: 1.99,
    color: 'from-red-500 to-red-700',
    icon: '💪',
    unlocked: false,
  },
  { 
    id: 3, 
    name: 'Master', 
    desc: 'Only the best survive',
    tensionMultiplier: 1.8,
    biteWindow: 0.8,
    fishStrength: 1.7,
    rewardMultiplier: 3.0,
    price: 2.99,
    color: 'from-purple-600 to-indigo-800',
    icon: '🏆',
    unlocked: false,
  },
  { 
    id: 4, 
    name: 'Legendary', 
    desc: 'Near impossible odds',
    tensionMultiplier: 2.2,
    biteWindow: 0.6,
    fishStrength: 2.0,
    rewardMultiplier: 5.0,
    price: 4.99,
    color: 'from-yellow-500 via-orange-500 to-red-600',
    icon: '⚡',
    unlocked: false,
  },
  { 
    id: 5, 
    name: 'IMPOSSIBLE', 
    desc: 'Are you insane?!',
    tensionMultiplier: 3.0,
    biteWindow: 0.4,
    fishStrength: 3.0,
    rewardMultiplier: 10.0,
    price: 9.99,
    color: 'from-black via-red-900 to-black',
    icon: '💀',
    unlocked: false,
  },
];

// ========== SINGLE ITEM CATEGORIES ==========
export const SINGLE_ITEMS = {
  stages: { name: 'Stages', icon: '🗺️', items: EXPANSION_STAGES },
  rods: { name: 'Rods', icon: '🎣', items: EXPANSION_RODS },
  bobbers: { name: 'Bobbers', icon: '🔴', items: EXPANSION_BOBBERS },
  lines: { name: 'Lines', icon: '🧵', items: EXPANSION_LINES },
  difficulties: { name: 'Difficulty', icon: '💪', items: EXPANSION_DIFFICULTIES },
  tacklebox: { name: 'Tacklebox', icon: '🎒', items: TACKLEBOX_UPGRADES },
};

